#!/usr/bin/env bash
#configures Domain zone

display_dns_info() {
    local subdomain=$1
    local domain=$2
    dns_info=$(dig "$subdomain"."$domain" | awk '/^;; ANSWER SECTION:$/,/^$/ {if (!/^;;/ && NF) print}')
    record_type=$(echo "$dns_info" | awk '{print $4}')
    destination=$(echo "$dns_info" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ $# -eq 1 ]; then
    display_dns_info "www" "$1"
    display_dns_info "lb-01" "$1"
    display_dns_info "web-01" "$1"
    display_dns_info "web-02" "$1"
elif [ $# -eq 2 ]; then
    display_dns_info "$2" "$1"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
