#!/usr/bin/env bash
#This script configures Nginx

sudo apt update

sudo apt install -y nginx

HOSTNAME=$(hostname)

sudo bash -c 'cat > /etc/nginx/conf.d/custom_headers.conf' <<EOF
server_tokens off;

server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	server_name _;

	add_header X-Served-By $HOSTNAME;

	location / {
		try_files $uri $uri/ =404;
	}
}
EOF

sudo nginx -t

sudo systemctl reload nginx
