#!/usr/bin/env bash
# a script that displays numbers from 1 to 100
for ((i=1; i<101; i++))
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
		continue
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
		continue
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
		continue
	else
		echo "$i"
		continue
	fi
done
