#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
while [ $i -lt 10 ];
do
	if [ $i -eq 8 ];
	then
		echo "Best School"
		echo "Hi"
		((i++))
		continue
	else
	echo "Best School"
	((i++))
	fi
done
