#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
while [ $i -lt 10 ];
do
	if [ $i -eq 3 ];
	then
		echo "bad luck"
		((i++))
		continue
	elif [ $i -eq 7 ];
	then
		echo "good luck"
		((i++))
		continue
	else
	echo "Best School"
	((i++))
	fi
done
