#!/usr/bin/env bash
#this script configures a container

sudo service nginx stop
sed -i 's#^listen\s*80;#listen 8080;#g' /etc/nginx/nginx.conf
sed -i '/^user/s/.*/user nginx;/' /etc/nginx/nginx.conf
service nginx start
